name: preview
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'creds.json'
      - 'dnsconfig.js'
jobs:
  preview:
    runs-on: ubuntu-latest
    container:
      image: ttkzw/dnscontrol
    steps:
      - uses: actions/checkout@v4
      - name: dnscontrol preview
        run: dnscontrol preview
        env:
          SAKURACLOUD_ACCESS_TOKEN: ${{ secrets.SAKURACLOUD_ACCESS_TOKEN }}
          SAKURACLOUD_ACCESS_TOKEN_SECRET: ${{ secrets.SAKURACLOUD_ACCESS_TOKEN_SECRET }}